import { Event, Profile } from '@/types'

export interface CalendarEventData {
  id: string
  name: string
  description: string
  date: string
  time: string
  duration: number
  location: string
  organizer: {
    name: string
    email: string
  }
  attendees: Array<{
    name: string
    email: string
  }>
  matches?: Array<{
    name: string
    score: number
  }>
}

/**
 * Generates a calendar-friendly filename from event name
 */
export function generateCalendarFilename(eventName: string): string {
  return `${eventName.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_')}.ics`
}

/**
 * Formats calendar description with matches and attendees
 */
export function formatCalendarDescription(
  baseDescription: string,
  matches?: Array<{ name: string; score: number }>,
  attendees?: Array<{ name: string }>,
  maxAttendeesToShow: number = 10
): string {
  let description = baseDescription || ''

  if (matches && matches.length > 0) {
    description += '\n\n🎯 YOUR MATCHES ATTENDING:\n'
    matches.forEach(match => {
      description += `• ${match.name} (${Math.round(match.score * 100)}% match)\n`
    })
  }

  if (attendees && attendees.length > 0) {
    description += `\n\n👥 OTHER ATTENDEES (${attendees.length} total):\n`
    attendees.slice(0, maxAttendeesToShow).forEach(attendee => {
      if (!matches?.find(m => m.name === attendee.name)) {
        description += `• ${attendee.name}\n`
      }
    })

    if (attendees.length > maxAttendeesToShow) {
      description += `... and ${attendees.length - maxAttendeesToShow} more attendees\n`
    }
  }

  description += '\n\nGenerated by HelloEveryone.fun - Smart Social Matching'
  return description
}

/**
 * Downloads a calendar file from the API
 */
export async function downloadCalendarFile(
  eventId: string,
  eventName: string,
  onSuccess?: () => void,
  onError?: (error: string) => void
): Promise<void> {
  try {
    const response = await fetch(`/api/calendar/event/${eventId}`, {
      method: 'GET',
      credentials: 'include',
    })

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(errorData.error || 'Failed to generate calendar file')
    }

    // Get filename from response headers or generate one
    const contentDisposition = response.headers.get('content-disposition')
    let filename = generateCalendarFilename(eventName)

    if (contentDisposition) {
      const filenameMatch = contentDisposition.match(/filename="(.+)"/)
      if (filenameMatch) {
        filename = filenameMatch[1]
      }
    }

    // Create and trigger download
    const blob = await response.blob()
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    window.URL.revokeObjectURL(url)

    onSuccess?.()
  } catch (error) {
    const errorMessage =
      error instanceof Error
        ? error.message
        : 'Failed to download calendar file'
    onError?.(errorMessage)
    throw error
  }
}

/**
 * Validates if user can download calendar for event
 */
export function canDownloadCalendar(userRsvpStatus?: string | null): boolean {
  return userRsvpStatus === 'going'
}

/**
 * Gets calendar app suggestions based on user agent
 */
export function getRecommendedCalendarApps(): Array<{
  name: string
  instructions: string
  icon: string
}> {
  const isIOS =
    typeof navigator !== 'undefined' &&
    /iPad|iPhone|iPod/.test(navigator.userAgent)
  const isAndroid =
    typeof navigator !== 'undefined' && /Android/.test(navigator.userAgent)
  const isMac =
    typeof navigator !== 'undefined' && /Macintosh/.test(navigator.userAgent)

  const apps = [
    {
      name: 'Google Calendar',
      instructions: 'Open the downloaded .ics file to import',
      icon: '📅',
    },
    {
      name: 'Outlook',
      instructions: 'Double-click the .ics file to add to Outlook',
      icon: '📧',
    },
  ]

  if (isIOS || isMac) {
    apps.unshift({
      name: 'Apple Calendar',
      instructions: 'Tap the downloaded file to add to Calendar',
      icon: '🍎',
    })
  }

  return apps
}

/**
 * Tracks calendar download analytics
 */
export function trackCalendarDownload(
  eventId: string,
  eventName: string
): void {
  if (typeof window !== 'undefined' && 'gtag' in window) {
    ;(window as any).gtag('event', 'calendar_download', {
      event_category: 'engagement',
      event_label: eventId,
      value: eventName,
    })
  }
}
