import { EventAttributes } from 'ics'

/**
 * Mock calendar data for testing
 */
export const mockCalendarEvent: EventAttributes = {
  start: [2025, 1, 15, 19, 0], // January 15, 2025, 7:00 PM
  end: [2025, 1, 15, 21, 0], // January 15, 2025, 9:00 PM
  title: 'Test Event - Coffee Meetup',
  description:
    'A test event for calendar integration\n\n🎯 YOUR MATCHES ATTENDING:\n• John Doe (85% match)\n\n👥 OTHER ATTENDEES (3 total):\n• Jane Smith\n• Mike Johnson\n\nGenerated by HelloEveryone.fun - Smart Social Matching',
  location: '123 Coffee St, City, State',
  url: 'https://helloeveryone.fun/events/test-event-id',
  organizer: {
    name: 'Test Organizer',
    email: 'organizer@test.com',
  },
  attendees: [
    { name: 'John Doe', email: 'john@test.com', rsvp: true },
    { name: 'Jane Smith', email: 'jane@test.com', rsvp: true },
  ],
  alarms: [
    {
      action: 'display',
      description: 'Reminder: Test Event starts in 1 hour',
      trigger: { hours: 1, minutes: 0, before: true },
    },
  ],
}

/**
 * Validates ICS content format
 */
export function validateIcsContent(icsContent: string): {
  isValid: boolean
  errors: string[]
} {
  const errors: string[] = []
  const lines = icsContent.split('\n')

  // Check for required components
  const requiredFields = [
    'BEGIN:VCALENDAR',
    'END:VCALENDAR',
    'BEGIN:VEVENT',
    'END:VEVENT',
  ]
  for (const field of requiredFields) {
    if (!icsContent.includes(field)) {
      errors.push(`Missing required field: ${field}`)
    }
  }

  // Check for DTSTART and DTEND
  if (!icsContent.includes('DTSTART:')) {
    errors.push('Missing DTSTART field')
  }
  if (!icsContent.includes('DTEND:')) {
    errors.push('Missing DTEND field')
  }

  // Check for SUMMARY (title)
  if (!icsContent.includes('SUMMARY:')) {
    errors.push('Missing SUMMARY field')
  }

  return {
    isValid: errors.length === 0,
    errors,
  }
}

/**
 * Extracts event details from ICS content for testing
 */
export function parseIcsContent(icsContent: string): {
  title?: string
  description?: string
  location?: string
  startTime?: string
  endTime?: string
  organizer?: string
} {
  const lines = icsContent.split('\n')
  const result: any = {}

  for (const line of lines) {
    const trimmedLine = line.trim()

    if (trimmedLine.startsWith('SUMMARY:')) {
      result.title = trimmedLine.substring(8)
    } else if (trimmedLine.startsWith('DESCRIPTION:')) {
      result.description = trimmedLine.substring(12)
    } else if (trimmedLine.startsWith('LOCATION:')) {
      result.location = trimmedLine.substring(9)
    } else if (trimmedLine.startsWith('DTSTART:')) {
      result.startTime = trimmedLine.substring(8)
    } else if (trimmedLine.startsWith('DTEND:')) {
      result.endTime = trimmedLine.substring(6)
    } else if (trimmedLine.startsWith('ORGANIZER:')) {
      result.organizer = trimmedLine.substring(10)
    }
  }

  return result
}

/**
 * Test calendar apps compatibility
 */
export const calendarAppTests = [
  {
    name: 'Google Calendar',
    testCases: [
      'Should accept standard ICS format',
      'Should display event title correctly',
      'Should show location and description',
      'Should set up alarms/reminders',
    ],
  },
  {
    name: 'Apple Calendar',
    testCases: [
      'Should import on iOS Safari',
      'Should import on macOS',
      'Should handle timezone correctly',
      'Should display attendees list',
    ],
  },
  {
    name: 'Outlook',
    testCases: [
      'Should import via double-click',
      'Should handle recurring events',
      'Should preserve organizer info',
      'Should work with Outlook web',
    ],
  },
  {
    name: 'Mozilla Thunderbird',
    testCases: [
      'Should import ICS files',
      'Should display all event details',
      'Should handle alarms correctly',
    ],
  },
]

/**
 * Performance benchmarks for calendar generation
 */
export const performanceBenchmarks = {
  icsGeneration: {
    maxTimeMs: 50, // ICS generation should be < 50ms
    description: 'Time to generate ICS content',
  },
  apiResponse: {
    maxTimeMs: 200, // API should respond < 200ms
    description: 'Time for calendar API to respond',
  },
  fileDownload: {
    maxTimeMs: 1000, // Download should start < 1s
    description: 'Time to initiate file download',
  },
}
